### ISSUE TITLE
Feature request: summary at end of prefill

### ISSUE THREAD

**Issue by dlrudie** [tpill90/steam-lancache-prefill#109]
At the end of the prefill it would be nice to have a short summary of what may have been skipped, downloaded, or updated. With a large library whenever I run prefill I just let it run its course and then afterwards I scroll up through the whole prefill to locate what got downloaded so I can see what has been updated since I last ran it.

If not a summary then perhaps maybe just not displaying titles that are up to date in the list. That way the only thing it will show are what it downloads. At the end you could have it show: "123 titles up to date, 14 titles skipped, 12 titles updated" or something along those lines.

Use case is that I use tmux and split everything into multiple windows. This means steam-prefill runs in a smaller overall console window so when trying to see what was updated there's more pages to scroll up through.

![image](https://user-images.githubusercontent.com/1780069/187706304-1ae166cb-deb4-481d-96dd-d1895321abae.png)

**Comment by tpill90** [comment]
Added a summary table at the end of the run 
![image](https://user-images.githubusercontent.com/766513/188231709-fde818e8-d8f9-4e36-9873-2ee0b813dab1.png)

**Comment by tpill90** [comment]
Added `--quiet` flag that will only show games that updated/failed/ or are unowned.  It will skip outputting logs for games already up to date.

![image](https://user-images.githubusercontent.com/766513/188233096-622d6a0d-319d-405b-9258-c083c2bf00fb.png)
