### ISSUE TITLE
OSX default terminal: PgUp PgDn does not work as expected

### ISSUE THREAD

**Issue by rwesterflan** [tpill90/steam-lancache-prefill#11]
Default terminal app just scrolls back/forth the console scrollback instead of scrolling through the list

**Comment by tpill90** [comment]
[SteamPrefill.zip](https://github.com/tpill90/steam-lancache-prefill/files/9169580/SteamPrefill.zip)

**Comment by tpill90** [comment]
@rwesterflan Could you give this a shot with `select-apps-beta` in the latest version? https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.3.2

**Comment by tpill90** [comment]
Closing as this is tested as working in 1.3.4
