### ISSUE TITLE
Certain games failing to download

### ISSUE THREAD

**Issue by dlrudie** [tpill90/steam-lancache-prefill#116]
I've ran into an issue just recently where three games in particular will fail to download consistently. I haven't had a chance to test every game in my library but so far I'm up to the R's in my library prefill and these are the only three titles that fail.

Tested with 1.4.0 and 1.5.0 and it behaves the same with both.

I have also ran clear-cache -y prior.

![image](https://user-images.githubusercontent.com/1780069/188197858-c9bc26c8-d45f-4a4f-ab82-862bd7146ef3.png)

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/189364114-0e4a9506-01cf-4626-a20c-2e4fd1169f36.png)

**Comment by tpill90** [comment]
[SteamPrefill-1.5.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9536315/SteamPrefill-1.5.0-linux-x64.zip)
[SteamPrefill-1.5.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9536317/SteamPrefill-1.5.0-win-x64.zip)
