### ISSUE TITLE
libicu is required to run the app

### ISSUE THREAD

**Issue by TurboSlayer** [tpill90/steam-lancache-prefill#12]
The package `libicu` is required to run the app. This means users who choose to run the app in a docker container will have to build their own image from a Dockerfile.

The full error given when trying to run the app without libicu installed: `Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.`

**Comment by tpill90** [comment]
Thank you for your help!  #15 has been merged in.

I will close this ticket out once I publish a new version with these changes.
