### ISSUE TITLE
Games downloading directly from downstream, bypassing LanCache

### ISSUE THREAD

**Issue by a2theziz** [tpill90/steam-lancache-prefill#124]
When downloading games, SteamPrefill is mostly bypassing the lancache and going straight to a CDN. When using steam directly or BattleNetPrefill, all downloads are served by LanCache.

DNS is correctly resolving to the LanCache IP. 

![image](https://user-images.githubusercontent.com/25150295/188331040-2e44df8c-077f-40e9-8569-4ad86fe09f1f.png)

Weird thing is, I'm not seeing any DNS queries that's resolving to the CDN I'm downloading from.

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/189451709-f18de3af-b58f-4b3b-83f8-168fabe2e0d8.png)
![image](https://user-images.githubusercontent.com/766513/189451724-19f9321a-4062-463d-a2c5-19ed14fa4e65.png)

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/189477202-9ed72668-1d32-4f56-acc9-a6f6afd4a263.png)

**Comment by tpill90** [comment]
[SteamPrefill-1.5.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9539923/SteamPrefill-1.5.0-win-x64.zip)
[SteamPrefill-1.5.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9539924/SteamPrefill-1.5.0-linux-x64.zip)

**Comment by tpill90** [comment]
Closing as this appears to be a regional issue with specific CDNs, and not specific to SteamPrefill
