### ISSUE TITLE
Implement auto-update script

### ISSUE THREAD

**Issue by soonic6** [tpill90/steam-lancache-prefill#129]
My Usecase:
I use prefill every night to pre fill my lancache. A cronjob starts up an LXC, runs an [update script](https://github.com/soonic6/steam-lancache-prefill-update), runs the prefill and shut the LXC down.

Motivation:
A version check is still implemented, but a quiet (maybe optional) autoupdate can be usefull for a headless lancache-prefill.

Maybe https://github.com/soonic6/steam-lancache-prefill-update could be implemented for auto-updates.

**Comment by tpill90** [comment]
### Implementation Tasks

- [ ] Scripts
	- [ ] Implement Bash based update script.  https://github.com/tpill90/steam-lancache-prefill/blob/master/scripts/update.sh
	- [ ] Implement Powershell based update script, for Windows.  https://github.com/tpill90/steam-lancache-prefill/blob/master/scripts/update.ps1
- [ ] Publish
	- [ ] Include `update.sh` in Linux, OSX, and ARM publish package
	- [ ] Include `update.ps1` in Windows publish package
- [ ] Documentation
	- [ ] Reference new update scripts in Updating section in readme https://github.com/tpill90/steam-lancache-prefill#updating

**Comment by ich777** [comment]
@tpill90 from the script that @soonic6 posted you can also hand over the current path from prefill directly to the script if that's something from interest, this is basically a install/update script on it's own.

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/194724300-a6a2b469-6b5b-4028-a5f8-3c17d7c0d690.png)

**Comment by tpill90** [comment]
Released in [v1.6.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.6.0)
