### ISSUE TITLE
Sea of Thieves download speed lower than expected

### ISSUE THREAD

**Issue by roope242** [tpill90/steam-lancache-prefill#132]
When downloading Sea of Thieves through Steamprefill on the machine hosting lancache, the speed is lower than expected.  
After a while the speed drops to around 70Mbit/s.  
I made sure it's not iowait that's messing up the speeds by monitoring with dstat.

Hardware used
```
i5 3570K
ASUS P8Z77V-LE
2X4GB Crucial Ballistix DDR3 1600 CL9
Samsung 970 Evo 500Gb
1Gbit LAN
600Mbit download
```

**Comment by roope242** [comment]
[SoTWorkload.tar.gz](https://github.com/tpill90/steam-lancache-prefill/files/9575777/SoTWorkload.tar.gz)
@tpill90 I here's the workload file as per your request.
I tested it today, and the results were the same. Speed starts at lower than expected, and falls to 70Mbit after a while.

**Comment by tpill90** [comment]
Closing as user no longer uses Lancache
