### ISSUE TITLE
Available Steam CDN servers exhausted

### ISSUE THREAD

**Issue by Joly0** [tpill90/steam-lancache-prefill#134]
![grafik](https://user-images.githubusercontent.com/13993216/190499981-79f90ab1-6cf1-45da-a571-d1146b9eb5d9.png)
![grafik](https://user-images.githubusercontent.com/13993216/190500232-81cb5dbe-76e7-4635-be67-2f2437c34d6d.png)
![grafik](https://user-images.githubusercontent.com/13993216/190500308-2cd19ca8-297d-40ed-ae5d-b891e770957e.png)

**Comment by tpill90** [comment]
Released in v1.5.2
