### ISSUE TITLE
[Bug] Arrow input is not responsive when prompted to "run prefill now"

### ISSUE THREAD

**Issue by Velosofy** [tpill90/steam-lancache-prefill#145]
Keyboard's arrow input doesn't do anything when it ask if you want to "run prefill now" after selecting apps using the beta UI.
Nothing works beside pressing enter which run prefill and terminating the program, like ctrl-c

Windows Command Prompt -> SSH to Linux/Debian 11
SteamPrefill version: 1.5.2-linux-x64

![image](https://user-images.githubusercontent.com/61261357/193426719-2626f754-6827-48b0-b48c-973b57811918.png)

**Comment by tpill90** [comment]
Released in v1.5.3
