### ISSUE TITLE
CDN servers exhausted! After download completion

### ISSUE THREAD

**Issue by C9Glax** [tpill90/steam-lancache-prefill#146]
After caching of larger games i get the error:
`Unexpected download error : Available Steam CDN servers exhausted!  No more servers available to retry!  Try again in a few minutes`
![grafik](https://user-images.githubusercontent.com/13404778/193476560-58c1fdb4-579c-4998-bb87-1949e783e6f1.png)

When I re-run `SteamCache prefill` it chews through the entire thing from the cache and then properly completes.

**Comment by C9Glax** [comment]
I think the problem is that if a request fails in the DownloadHandler, the Connection is not handed back to the pool. Subsequent failures drain the pool. Will get a pull ready in the next hour or so...

**Comment by tpill90** [comment]
This issue should be resolved with #166, and was released in [v1.6.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.6.0)
