### ISSUE TITLE
Frezzing when getting CDNs

### ISSUE THREAD

**Issue by kp2341** [tpill90/steam-lancache-prefill#170]
Hi, This new steam-prefill is great in general much improved over lancache autofill....however every so often it freezes on getting available CDN's and I have to re-run nohup ./SteamPrefill prefill --all &    , I'm running on Ubuntu Server inside a VM on TrueNAS core 13.0-U2.

**Comment by tpill90** [comment]
Released in v1.7.0 https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.7.0
