### ISSUE TITLE
Sorting should be done case-insensitive

### ISSUE THREAD

**Issue by rwesterflan** [tpill90/steam-lancache-prefill#18]
Right now, it's sorted A-Z.a-z,0-9, would be nice if everything was sorted if it were lowercase. Or uppercase. Whichever you prefer ;)

**Comment by tpill90** [comment]
Examples of titles affected by the sorting:
![image](https://user-images.githubusercontent.com/766513/181371850-c91924b9-97e7-43fa-bf4b-779b3580b86a.png)
![image](https://user-images.githubusercontent.com/766513/181371903-f3f44443-2398-483f-8134-332c4e77da4c.png)

**Comment by tpill90** [comment]
Fixed in #24 
![image](https://user-images.githubusercontent.com/766513/181372819-5a44762c-b4e2-4e95-b8f9-5062881149b2.png)

**Comment by tpill90** [comment]
Released in [v.1.2.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.2.0)
