### ISSUE TITLE
Error while downloading manifests Dota 2 and PUBG

### ISSUE THREAD

**Issue by Fallen9218** [tpill90/steam-lancache-prefill#187]
Good afternoon, I get an error, Error while downloading manifests Dota 2 and PUBG
![Без названия](https://user-images.githubusercontent.com/116370504/197227505-28351645-5729-43dc-98ef-7058b592c6fc.png)
[errorlog.txt](https://github.com/tpill90/steam-lancache-prefill/files/9840255/errorlog.txt)

**Comment by kizmat** [comment]
![retry Screenshot 2022-10-21 185606](https://user-images.githubusercontent.com/20874536/197249554-4387e8ad-ce54-4396-b19a-7af5b0ae67b7.png)
![retry Screenshot 2022-10-21 185737](https://user-images.githubusercontent.com/20874536/197249559-fba99215-50c7-40be-b6a9-a08396730a67.png)
![retry Screenshot 2022-10-21 185817](https://user-images.githubusercontent.com/20874536/197249562-d6bd85f7-25d0-4635-8e3a-6a529e7413bc.png)
![Screenshot 2022-10-21 184856](https://user-images.githubusercontent.com/20874536/197249564-275a72d9-8223-4c1f-81fd-490911a3a261.png)
![Screenshot 2022-10-21 185318](https://user-images.githubusercontent.com/20874536/197249567-165c6296-4df7-4a25-acd8-53fa83c115cc.png)

DOTA 2, will not complete downloading it will just stop

**Comment by kizmat** [comment]
The manifests issue has been reported in issue #175

**Comment by tpill90** [comment]
I'm closing this issue as from our discussions on Discord it appears to be resolved.

If the issue reoccurs, please feel free to reopen.
