### ISSUE TITLE
feature request: errorlog.txt does include time stamps

### ISSUE THREAD

**Issue by kizmat** [tpill90/steam-lancache-prefill#191]
I would really appreciate timestamps in the error log (errorlog.txt).
This makes it easier to diagnose/resolve issues.

And if at all possible would be nice to improve the log formatting to make it more readable.

Cheers!

**Comment by Velosofy** [comment]
If you haven't noticed, you opened 2 issue tickets

**Comment by kizmat** [comment]
duplicate issue
