### ISSUE TITLE
New Modern Warfare II not downloading all data

### ISSUE THREAD

**Issue by EthRousseau** [tpill90/steam-lancache-prefill#200]
Just got the new MWII and went to prefill it, so I could download it fast when I got home. The select apps menu only shows that the game is 15GB, and when run, only downloads 15GB. The issue is the game on steam is reporting that the game takes up 55GB. When I did go and download it from steam, it got the first 15GB at full 2.5Gb speed (i.e. from the cache), and got the rest at ISP speed.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/41489473/198902275-5ee53716-d94b-41e0-8739-afa501997922.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/41489473/198902287-c0d72245-143a-4bb5-b648-7783b2182be8.png">

SteamDB Link: https://steamdb.info/app/1938090/depots/

**Comment by tmontney** [comment]
Seeing that issue here as well as with Halo: Infinite. Downloads just about 20.13 GiB, but fails at the end. Retries a few times to download 19 MiB, then says "23 failed downloads". For MW2, the download speed is abysmal. Should be getting 100 MB/s, only seeing around 5 MB/s. No other prefill has this issue.

(With the latest version of prefill, can't seem to CTRL+C/CTRL+Z to cancel the download anymore.)

**Comment by tmontney** [comment]
Seems to also affect LanCache. Came home today and the download was stuck at ~12 GB. Switched from LanCache DNS and it resumed.

**Comment by tpill90** [comment]
I've done some deeper digging, and it looks like you're right @tmontney.  Both Halo Infinite and Dota 2 seem to be affected by the same issue.

I checked my library to see how many games are affected in my library, and I found the following 36 games : 
![image](https://user-images.githubusercontent.com/766513/201247693-921a93bf-2f9e-4fa5-a34c-7d9a994b1283.png)

**Comment by tpill90** [comment]
## [Halo Infinite](https://steamdb.info/app/1240440/depots/)

| Expected | Current |
| --- | --- |
|      |       |

**Comment by tpill90** [comment]
Before and after the fix:
![image](https://user-images.githubusercontent.com/766513/201267957-a9987984-9d10-4974-bd52-1fa0561a2732.png)

**Comment by tpill90** [comment]
Actual download sizes as reported by Steam
![image](https://user-images.githubusercontent.com/766513/201268343-2218bc60-fe32-4cd6-82ea-ab4b8284d97d.png)

**Comment by tpill90** [comment]
@EthRousseau @tmontney Here's a test build with the fix if you guys want to give it a shot https://github.com/tpill90/steam-lancache-prefill/actions/runs/3446256783

**Comment by tpill90** [comment]
Released in [v1.8.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.8.0)

**Comment by tmontney** [comment]
Sorry for the delay, will check out the latest release.

**Comment by tmontney** [comment]
Size looks correct now but download speed is abysmal.

- Prefill barely refreshes
- Download ETA looks like
```
Downloading.. ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% **:**:** 0.1/54.3 GiB 378.0 Kbit/s
```
- Still seeing "MISS 502" in the logs

**Comment by tpill90** [comment]
@tmontney Just to clarify, it sounds like the problem reported in this issue is resolved for you?  And you're running into a separate issue with your cache being bypassed?

**Comment by tpill90** [comment]
Closing this issue as it seems to be resolved.  Please feel free to re-open if anything changes
