### ISSUE TITLE
Tag to pull most recently played games regardless of time?

### ISSUE THREAD

**Issue by reg98643t** [tpill90/steam-lancache-prefill#205]
Could the "Recent" tag or a new tag pull the last few games played without the "in the last two weeks" qualifier?

So if I played 10 games in a year and did --recent it would pull those games?

Could just be me but I use Lancache to prefetch game updates so when I have time to game once in a blue moon the updates are at my home network speed rather than the internet connection speed. In my case "played in the last two weeks" would usually be 0 games.

**Comment by tpill90** [comment]
@reg98643t From my understanding, it sounds like you're asking for `--recent` to be able to query different time periods, such as `2 weeks` `6 months` `1 year` `2 years`, is that correct?

Steam only keeps track of playtime in two categories,  `2 weeks` and `All Time`, so those two would be the only time ranges that would be possible.

**Comment by tpill90** [comment]
Closing this as time ranges will not be possible to implement.
