### ISSUE TITLE
Tag to download most recently purchased games?

### ISSUE THREAD

**Issue by reg98643t** [tpill90/steam-lancache-prefill#206]
I schedule Steam Prefill to check for updates every few hours. Be nice to buy a game while I'm out and have it ready to go when I get home.

**Comment by FreelancerJay** [comment]
Agreed, this would be very useful for home users

**Comment by tpill90** [comment]
While this is technically possible, after some consideration I have decided that this will not be implemented.  

Steam does return this information when logging into an account, however propagating this information throughout SteamPrefill would add a non-trivial amount of complexity.  This complexity is what gives me pause on implementing this feature.

Setting this issue as closed for now.
