### ISSUE TITLE
Prefilling on previously cached games runs again

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#209]
I just updated to the latest version and now I am experiencing this issue as well. Was working fine prior to update.

_Originally posted by @reg98643t in https://github.com/tpill90/steam-lancache-prefill/issues/114#issuecomment-1306422827_

**Comment by tpill90** [comment]
It might be easier for you @reg98643t to message me on Discord so we can chat about this.  My username on Discord is the same as my Github username

**Comment by RiDDiX** [comment]
I have the same problem.

**Comment by reg98643t** [comment]
I fixed it by deleting everything to do with prefill, installing it fresh and then running prefill again. It had to "download" the files again but when it was done it was working properly again.

**Comment by RiDDiX** [comment]
This means you completely deleted the lancache?

**Comment by reg98643t** [comment]
No, just the files associated with the prefill program.

**Comment by tpill90** [comment]
@reg98643t @reg98643t It sounds like everything eventually resolved itself for you.  Thinking about this some more, I believe that I accidentally caused this for some people when I moved the file that tracks previous downloads out of the `Cache` dir into the `Config` dir : https://github.com/tpill90/steam-lancache-prefill/issues/202

The intention for doing this was actually to hopefully avoid this exact scenario in the future, so I apologize for the confusion about it.

I'm going to close this issue for now, but please feel free to reopen it if anything changes.
