### ISSUE TITLE
lancache-prefill crash start prefill or select-apps

### ISSUE THREAD

**Issue by soonic6** [tpill90/steam-lancache-prefill#218]
![image](https://user-images.githubusercontent.com/73687921/201751195-2976baf6-42e9-4675-b2f5-545852300420.png)

![image](https://user-images.githubusercontent.com/73687921/201751315-86f16f70-c774-40e4-8391-8d9e5e045a25.png)

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/202302773-4a468c3f-ceec-45b5-86d3-6fb52e2038fa.png)
Added a better error message

**Comment by tpill90** [comment]
Released in [v1.8.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.8.0)
