### ISSUE TITLE
Is it possible to implement --no-ansi application wide

### ISSUE THREAD

**Issue by ich777** [tpill90/steam-lancache-prefill#219]
Hi,
is it possible to integrate `--no-ansi` application wide, currently it only supports `prefill` from my testing, see attached screenshot:
![image](https://user-images.githubusercontent.com/28066518/201754722-9cbeba9a-b332-49f0-9e30-f4a867792a19.png)

Cheers,
Christoph

**Comment by tpill90** [comment]
Released in [v1.8.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.8.0)
