### ISSUE TITLE
Feature Request: A option to silent output for batch/cron usage

### ISSUE THREAD

**Issue by bufanda** [tpill90/steam-lancache-prefill#232]
I have setup a cron job to update pre cached games periodically and also setup cron to email me outputs prefill is pretty verbose which is ok when I sit in front of the computer, but an option to lower verbosity or disable output alltogehter (maybe except the summary) would be nice for usage in a cron job and mail setup as the mail gets pretty big.

Maybe also a logging function to log to a logfile only would be a nice addition.

**Comment by tpill90** [comment]
Have you tried running prefill with the `--no-ansi` flag?  It will make it so that the progress bar is no longer displayed, and everything output should be in plaintext.  
![image](https://user-images.githubusercontent.com/766513/207175410-2a433acd-65a1-43fe-a9b5-1889865a4824.png)

**Comment by tpill90** [comment]
Closing as the `--no-ansi` flag should cover this use case.  If it doesn't, please feel free to reopen
