### ISSUE TITLE
Error when downloading a game from prefill

### ISSUE THREAD

**Issue by nath2125** [tpill90/steam-lancache-prefill#235]
Had an issue pop up when running the manual prefill lancache containers. 

"An unexpected error (System.Net.Http.HttpRequestException) occurred while downloading manifests. Retrying..."

I have ran this within unraid termainal:
```
docker run -it --rm \
  --net=br0 \
  --add-host=lancache.steamcontent.com:XXX.XXX.XXX.XXX  \
  --volume ~/.config/SteamPrefill:/Config \
  tpill90/steam-lancache-prefill:latest \
  select-apps
```
and adding my ip for lancache ofc

Still end up with the same error message as when I was running the other container from ich777
![image](https://user-images.githubusercontent.com/99367069/207673551-85f2aad2-04fa-4a34-9027-e37b91959896.png)

**Comment by nath2125** [comment]
Forgot to screenshot the photo from the tpill90 steam lancache docker run but throws the same erros as above.

**Comment by tpill90** [comment]
Closing as user reports issue no longer occurs
