### ISSUE TITLE
Unable to connect, transient error with Steam Network

### ISSUE THREAD

**Issue by vastofficial** [tpill90/steam-lancache-prefill#237]
**After selecting the games to download, I get this error:**
`Unable to load latest App metadata! An unexpected error occurred! 
This could possibly be due to transient errors with the Steam network. 
Try again in a few minutes.
[2:01:31 AM] Disconnected from Steam!
prefill@b9d56f2489ff:~/SteamPrefill$ `

**Comment by jcfrosty** [comment]
same

**Comment by billthecatt** [comment]
Suggest there be some debug output in the program that makes it clear which hostname is causing a given error so we can troubleshoot the issues in dns that seem to regularly occur with lancache setups.

**Comment by tpill90** [comment]
Closing this as I have not received any additional information.
