### ISSUE TITLE
Double-clicking app doesn't behave like expected

### ISSUE THREAD

**Issue by Velosofy** [tpill90/steam-lancache-prefill#256]
the current release of prefill v1.9.0 adds detection to show warning if the app is launched from a double click
In my testing, this doesn't behave as expected - the app will open a terminal window for a brief moment and closes.

I have Windows 11 22H2 22621.963

**Comment by tpill90** [comment]
Released in [v1.9.1](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.9.1)
