### ISSUE TITLE
Auto-cache recently purchased/added games

### ISSUE THREAD

**Issue by Mavyre** [tpill90/steam-lancache-prefill#265]
I love to use the lancache autofill to cache the recently played games using --recent. It allows me to have fast updates from the game I usually play. However, I'd love to also do Prime Caching on the games I purchased before downloading them. That would allow to automatically pre-download games without having to think about it!

**Comment by tpill90** [comment]
So to clarify my understanding, you're looking to have a feature that does the same as `--recent`, however it should use your purchase history instead?

It sounds to be very similar to this request #206

**Comment by Mavyre** [comment]
This indeed is the same request. Didn't found it while searching for it,
sorry about that.

**Comment by tpill90** [comment]
Closing as wont fix.
