### ISSUE TITLE
Greek instructions

### ISSUE THREAD

**Issue by comfuzio** [tpill90/steam-lancache-prefill#266]
Hi!
I know Greek ain't a popular language for the past 700 years and I guess we aren't a big community but I made a guide in Greek
[](https://e-arena.gr/guides/steam-lancache-prefill/)
I will help with the adaptation to the page if/when needed!

**Comment by tpill90** [comment]
Closing this out as I added support for multiple languages on the docs in #288 

The translations can come whenever you're able to get around to them 😄
