### ISSUE TITLE
Feature request - Total data downloaded 

### ISSUE THREAD

**Issue by billthecatt** [tpill90/steam-lancache-prefill#267]
If you could, print this at the end of each run, then we could see what du -h shows and compare to see what's in the cache on disk vs just now downloaded.

**Comment by tpill90** [comment]
Added ![image](https://github.com/tpill90/steam-lancache-prefill/assets/766513/707f4681-2e8c-410f-877d-622f6f9a7d9d)

**Comment by tpill90** [comment]
Released in [v2.2.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.2.0)
