### ISSUE TITLE
Failed Downloads

### ISSUE THREAD

**Issue by bgraf2311** [tpill90/steam-lancache-prefill#270]
Some games are getting failed downloads using the Steam prefill causing prefill on subsequent runs to attempt to download them all over again (even from LANcache this can take a long time for big games). The failed downloads range from only 1 or 2 to a few thousand. It varies with different games. 

Tailing the access.log in LANcache will often show the same chunk of data being attempted to be downloaded from different CDNs. There will be a pause and you can see it switch to a different region. These failures are usually all marked as HITs in the access log.

Things attempted to resolve/troubleshoot:
Client/PC restart
Restarting LANcache/Steam prefill
Removing/adding in problematic games from the select-apps menu

Temporary work-around:
Uninstalling and reinstalling the game in the Steam client (sometimes this allows prefill to complete for a particular game but not always)

**Comment by tpill90** [comment]
@bgraf2311 Is this issue still happening for you?

**Comment by bgraf2311** [comment]
I'll have to check it when I'm at home.

**Comment by bgraf2311** [comment]
I haven't really used it since the last LAN party. I can poke it later.

**Comment by tpill90** [comment]
@bgraf2311 I'm going to close this out for now, doing some housekeeping on the issues.  If you run into this issue again, feel free to reopen and I'll take another look.
