### ISSUE TITLE
Can you do the same for xbox games / xbox gamepass pc ?

### ISSUE THREAD

**Issue by draco1544** [tpill90/steam-lancache-prefill#274]
Can you do a project to prefill  xbox games / xbox gamepass pc ?

**Comment by tpill90** [comment]
There certainly is some demand for one!  I've heard from others that they would be interested in it.

Unfortunately I don't have the time to take on another one of these, I have my hands full supporting the 3 that already exist.  Perhaps sometime in the future 😄
