### ISSUE TITLE
Change between 1.9 and 1.9.1 causing "No Lancache Found"

### ISSUE THREAD

**Issue by dj3520** [tpill90/steam-lancache-prefill#281]
Running my own custom configuration without docker so I wouldn't be surprised if this is something odd on my end, but versions after 1.9.1 report that my lancache server can't be found. The specific error message:

` Error!  lancache.steamcontent.com is resolving to a private IP address (192.168.5.7), however no Lancache can be found at that address.  The Lancache server may possibly not be running. Please check your configuration, and try again.`

The steam client as well as SteamPrefill 1.9 are working fine, so I'm suspecting whatever changes happened in version 1.9.1. Let me know if there's any tests, logs, or config files you'd like.

**Comment by tpill90** [comment]
@dj3520 From what you've posted so far, I'm assuming you're running SteamPrefill directly on your cache host correct?  How many IP addresses do you have assigned to that host? Which IP is monolithic bound to?

If I had to wager a guess, you do indeed have multiple IPs, and monolithic is using an IP that's higher up than 192.168.5.7 right?

**Comment by dj3520** [comment]
SteamPrefill operates the same whether running on the same machine or a separate computer. Same behavior with both versions in fact. 1.9 is happy to run, while 1.9.1 and higher gives this error message.

.5.7 is the correct address. I'm not running any docker container and all caches (for multiple services) are all at .5.7 and working correctly. 

If you'd like I am in the Discord under the same username and would be fine discussing this there if it's easier.

**Comment by tpill90** [comment]
Potentially related to the changes introduced in #260

**Comment by dj3520** [comment]
Closing as issue is largely due to my custom server setup. For later reference, it was caused by sending requests to the IP address directly instead of via the hostname, and my nginx setup wasn't handling that. Specifically `/lancache-heartbeat` would 404 _except_ when asked as `lancache.steampowered.com/lancache-heartbeat` and only when asked by IP address. Adding another virtual server that would respond correctly without a Host in the header of the request has fixed the issue and all is now well.
