### ISSUE TITLE
Games not Caching

### ISSUE THREAD

**Issue by Madcat3108** [tpill90/steam-lancache-prefill#297]
2 Games in my list are not caching.

I get the following message:

[8:29:16 PM] Starting HITMAN 3  No depots to download.  Current arguments filtered all depots
[8:29:16 PM] Starting Rogue Tower  No depots to download.  Current arguments filtered all depots
[8:29:16 PM] Prefill complete!

Steam GameID according to the .json are (confirmed in steamapps/common/xxx.acf)
1659040 = Hitman 3
1843760 = Rouge Tower

In Steam, both games dl fine.
Other games cache well, tested with CS:GO, Half-Life2,  ARK Survival Evolved, MS Flightsim or PUBG
some of which are already precached, but others weren't.

Prefill is running on a bare metal Ubuntu 20.04 system

**Comment by tpill90** [comment]
Appears to be related https://github.com/SteamRE/DepotDownloader/issues/426

**Comment by tpill90** [comment]
Released in [v2.1.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.1.0)
