### ISSUE TITLE
SteamPrefill and BattleNetPrefill in the same folder causes issues

### ISSUE THREAD

**Issue by crkinard** [tpill90/steam-lancache-prefill#304]
It would be nice for SteamPrefill and BattleNetPrefill to play nice when in the same folder.
As it is their Cache folders clash. SteamPrefill crashes and throws errors if BattleNetPrefill was run before it.

**Comment by crkinard** [comment]
Current work around is to use BattleNetPrefill with the -p option to specify which games to prefill. Doing this BattleNetPrefill does not write out to the cache so SteamPrefill can use it and functions fine.

**Comment by ich777** [comment]
@crkinard aren't these two separate applications and shouldn't they be separated anyways, I assume you don't have one shared folder for your Battle.net and Steam games or do you?

Maybe create a folder structure like this:
```
..|
  |-prefill
    |-battlenet
      |-folders...
      |-files...
    |-steam
      |-folders...
      |-files...
..
```
