### ISSUE TITLE
Control + C doesn't pause prefill after select-apps

### ISSUE THREAD

**Issue by DecusAnima** [tpill90/steam-lancache-prefill#305]
Control + C does not pause the prefill if it started after select-apps command is ran. Reboot necessary to stop the prefill.

**Additional Details**
 - Ubuntu 22.02 Server
 - decusanima
 - US Central

**Comment by tpill90** [comment]
Some additional notes on reproducing this

| Operating System | Command | Is able to be cancelled? | 
| --- | --- | --- |
| Windows | prefill | Yes |
| Windows | select-apps | Yes |
| Linux | prefill | Yes |
| Linux | select-apps | **No** |

**Comment by tpill90** [comment]
This is being caused by the changes from this issue https://github.com/tpill90/steam-lancache-prefill/issues/176

**Comment by tpill90** [comment]
Reopening this as the fix caused a regression for the issue #176 .  I'm going to revert this change for now and come back to this in the future.

**Comment by tpill90** [comment]
![image](https://github.com/tpill90/steam-lancache-prefill/assets/766513/1ae0112e-cab2-412d-905e-98d1ceca02ac)

**Comment by tpill90** [comment]
| Distro | $TERM |
| --- | --- |
| | linux |
| Ubuntu 20.04 | xterm-256color |

**Comment by tpill90** [comment]
Should be released in [v2.2.2](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.2.2)
