### ISSUE TITLE
Alternative sorting methods for game selection

### ISSUE THREAD

**Issue by EthRousseau** [tpill90/steam-lancache-prefill#31]
Sorting games by most recently played would help speed up the init for the games to prefill. 

People with huge libraries could be scrolling for quite some time before finding the 20 out of 200 games that they want to prefill, having the games you want to play the most right at the top would be great for speeding that up.

**Comment by tpill90** [comment]
Added a recent playtime column to `select-apps-beta`, as well as the ability to sort by playtime
![image](https://user-images.githubusercontent.com/766513/186674834-59b96cca-0f60-4ca0-b039-8e8bb5fa4726.png)
