### ISSUE TITLE
SteamPrefill not found - waiting isntall

### ISSUE THREAD

**Issue by Watever44** [tpill90/steam-lancache-prefill#310]
I just did a fresh install.
Seems like I am unable to download the steam prefill. Seems to work for the EpicPrefill but not the steam.
I am not sure why exactly. Can't find out why. I waited and waited.

![image](https://github.com/tpill90/steam-lancache-prefill/assets/97079352/0d0677d3-3d38-4563-b334-7c5b34716501)

Even when restarting the container, I get the same issue. Any idea what could be wrong ? My lancache and lancache-dns are both running. I have adguard-home running, I enabled/disabled, without changing anything. If I knew where it should be downloading, I could ping or force it may be.

**Comment by Watever44** [comment]
Look like it ended up downloading it. Took forever for a 59mb folder, while the epic folder is 29mb and took seconds.

I will leave it here for the next one having issue.

**Comment by tpill90** [comment]
Seems like this was just a transient issue with the download.  Closing this for now

**Comment by Watever44** [comment]
Not sure if it's related to that issue. But I am unable to sign to plex or epic for selecting games. It's long before I can enter my login, sometimes doesn't work, and then I enter my credentials and it will say disconnect for taking too long. I will sometimes get a request in my steam account just before but not always. 

I am wondering if it's due to the cache dns lan and adguard or something because I am in Canada ?

**Comment by tpill90** [comment]
If more than just SteamPrefill is being affected by things then I suspect that there is an issue going on with your DNS setup.  If you disable Lancache DNS does this issue go away?
