### ISSUE TITLE
`benchmark setup --use-selected` fails if `select-apps` is not ran first

### ISSUE THREAD

**Issue by MatiasLGonzalez** [tpill90/steam-lancache-prefill#311]
**Describe the bug**
If you run `benchmark setup --use-selected` without previously running `select-apps`, the program will exit with the error "`Benchmark file not built!  All apps were unowned and could not be included!`" which could be more intuitive.

**Additional Details**
 - Platform you are running SteamPrefill on:  Windows
 - Discord Username (if you are part of the Lancache Discord Server) : matiaslgonzalez
 - Region : South America

**Screenshots**
![imagen](https://github.com/tpill90/steam-lancache-prefill/assets/48534497/8dc736fb-5d52-438d-bf3e-7ee0d23a51f8)

**Comment by tpill90** [comment]
Released in [v2.2.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.2.0)
