### ISSUE TITLE
[Enhancement] show average download speed

### ISSUE THREAD

**Issue by Sysadminfromhell** [tpill90/steam-lancache-prefill#316]
**Describe the bug**
When Steamprefill installed as server (or run normally) it doesnt show average download speed.
For me and my application it would be really helpful to see with how much the download(s) were completed.

**Comment by tpill90** [comment]
This is when you're running it as a scheduled job? Are you using ich777's container?

**Comment by Sysadminfromhell** [comment]
Im not using any container, its the "nativ" linux executable.

**Comment by tpill90** [comment]
Could you post your log output here? The logs where you're missing the average

**Comment by Sysadminfromhell** [comment]
ah nevermind, its there I just didnt see it in the logs only via "journalctl"
```
Jul 04 21:29:21 HMLGame01 SteamPrefill[542]: [9:29:21 PM] Finished in 10:19.55 - 500.74 Mbit/s
Jul 04 21:29:21 HMLGame01 SteamPrefill[542]: [9:29:21 PM] Prefill complete!
```
