### ISSUE TITLE
`8 Failed Downloads` When Prefilling Remnant II

### ISSUE THREAD

**Issue by krishsai7** [tpill90/steam-lancache-prefill#317]
**Describe the bug**
Having a small issue with Remnant II prefill, it seems like for whatever reason the game prefills, attempts to download something extra? and then fails to do so but I'm not sure what it is. Debug isn't telling me which exact download failed however. Haven't seen this issue prior with other games (Remnant 1, God of War, etc.)

**Additional Details**
 - Platform you are running SteamPrefill on:  Ich777's Unraid App
 - Discord Username (if you are part of the Lancache Discord Server) : krishna
 - Region : US East

![image](https://github.com/tpill90/steam-lancache-prefill/assets/23455559/e4b462de-9d88-43f5-a0dc-83e33e70c09b)

**Comment by devanteweary** [comment]
Hey I have pretty much the same issue with several games.

Seems to fill up to about 99%ish, then flashes retrying a couple of times, then shows me "# failed downloads" and the little chart at the bottom won't count those as updated.

Then the next time I try, it starts those downloads over.

**Comment by tpill90** [comment]
@krishsai7 Is this still happening?

**Comment by krishsai7** [comment]
Seems to have resolved itself a couple days ago, I no longer see error logs when pre-filling. Not sure if there's anything you can add for debugging reasons now but I can let you know the next time a game has an issue like this.
