### ISSUE TITLE
Feature request: allow manual selection of steam download region

### ISSUE THREAD

**Issue by TurboSlayer** [tpill90/steam-lancache-prefill#32]
Some users may prefer to be able to select a specific download region for various reasons such as maximising bandwidth.

**Comment by dlrudie** [comment]
Second this. If I ever get any of the *LAX* content servers my downloads crawl <40mb/s while others closer to me get >900mb/s.

**Comment by tpill90** [comment]
### Implementation tasks
- [ ] Add a new flag `--region` that allows passing a cellid to specify which region to use for downloads
- [ ] Update readme.md to include new flag, and how it should ideally never be specified, except in certain cases where you might know there is a better server
- [ ] Add a new .md doc that lists the known servers

**Comment by tpill90** [comment]
Updated docs : https://github.com/tpill90/steam-lancache-prefill/tree/issues/32-ChooseDownloadRegion

Test build : 
[SteamPrefill-1.4.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9472186/SteamPrefill-1.4.0-win-x64.zip)
[SteamPrefill-1.4.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9472187/SteamPrefill-1.4.0-linux-x64.zip)
