### ISSUE TITLE
Running Steamprefill (Lancache resolving to a public ip)

### ISSUE THREAD

**Issue by ThePilger** [tpill90/steam-lancache-prefill#326]
When i start Steamprefill, i get an error Lancache is resolving to a public ip.

im using @Ich777 unraid lxc Container. 

![IMG_4086](https://github.com/tpill90/steam-lancache-prefill/assets/111175089/0493a70b-d656-4d6b-9a63-49457d7f01c5)

**Comment by ich777** [comment]
Are you using LXC on Unraid?

Can you post your Docker run command? Can you give a bit more details on your setup please?

**Comment by ThePilger** [comment]
docker run -d --name='LANCache' \
  --net='bridge' \
  -e CACHE_DISK_SIZE="4000000m" \
  -e CACHE_INDEX_SIZE="1000m" \
  -e CACHE_MAX_AGE="3650d" \
  -e TZ="Europe/Vienna" \
  -v '/mnt/lancache/cache':'/data/cache':'rw' \
  -v '/mnt/lancache/logs':'/data/logs':'rw' \
  -p 80:80 -p 443:443 \
  --no-healthcheck --restart=unless-stopped \
  'lancachenet/monolithic'

i followed your tutorial on Unraid.net and the last few weeks everything worked perfectly fine. Yesterday my server crashed and now i get this error adguard and unbound works perfectly fine.

**Comment by ich777** [comment]
Are you on Unraid 6.12.4?

Do you use IPVLAN for Docker on Unraid or do you run it without bridging, so to speak MACVTAP?

May I ask why you run LANCache also in the LXC container?
I would rather recommend that you run it in the Docker container directly on Unraid because it will not male muh difference and is easier to maintain on Unraid because of the GUI and autoupdates from container (if enabled).

**Comment by ThePilger** [comment]
i fixed it, nginx used port 80. Yesterday i installed Nginx to use DoH from outside and i couldnt get it to work so i deleted it but some files where left. After completely removing it, it works again. My bad should have check this first but didnt think about it anymore.

**Comment by mitch030504** [comment]
sorry to hijack the issue but i have the same problem and im using unraid. docker is configured with ipvlan.

**Comment by ich777** [comment]
@mitch030504 this is most of the times a miss configuration from the lancache containers and not strictly speaking from steam-prefill.

Is your lancache working on your local computer? If not please try to troubleshoot that in the first place.
