### ISSUE TITLE
Download Freezes during Pre-FIll

### ISSUE THREAD

**Issue by medic4085** [tpill90/steam-lancache-prefill#331]
Platform: Unraid

Issue:  Was able to run the commands successfully to log in and select the games for prefill.  During Download, it appears that the program "freezes" and does not continue to download.  I verified the network adapter in un-raid and can confirm that the download traffic stops.  Any thoughts...?

![image](https://github.com/tpill90/steam-lancache-prefill/assets/56422868/aeb45abf-b9d9-40f3-9341-3ed18b839e8a)

**Comment by medic4085** [comment]
Added Log from Docker.  
[0130397a143b646e67e0ea04531427a6cf81ae312e9632e1c5f3585eca00650c-json.log](https://github.com/tpill90/steam-lancache-prefill/files/12859025/0130397a143b646e67e0ea04531427a6cf81ae312e9632e1c5f3585eca00650c-json.log)

**Comment by tpill90** [comment]
@medic4085 Is this still a recurring issue for you?

**Comment by tpill90** [comment]
Closing since there has been no further response.
