### ISSUE TITLE
Colours in terminal which do not support it

### ISSUE THREAD

**Issue by Bastians-Bits** [tpill90/steam-lancache-prefill#339]
**Describe the bug**
In an automated workflow, the additional characters for colours in the terminal can interrupt the rendering of the text.

In my context, I am using unraid and added a script to run nightly and inform me about the updates via email.

**Additional Details**
 - Platform you are running SteamPrefill on: manually installed into lancachenet/monolithic:latest on unraid
 - Discord Username (if you are part of the Lancache Discord Server) : n/a
 - Region: curious why that has any relevance for a bug?

**Screenshots**
<img width="535" alt="Screenshot 2023-12-24 at 21 45 40" src="https://github.com/tpill90/steam-lancache-prefill/assets/51163929/73a3bbd0-1fd6-4aef-baf2-3449d66de860">
<img width="1040" alt="Screenshot 2023-12-24 at 21 43 40" src="https://github.com/tpill90/steam-lancache-prefill/assets/51163929/b8ef98f3-fbd7-4a9d-a196-34e76c027d0e">

**Script in question**
```
#!/bin/bash
#name=Lancache Autoupdate
#description=Use Lancache Prefill to auto-update all applications

log=/tmp/lancache-autoupdate_$(uuidgen)
touch $log

docker_id=$(docker ps --filter=ancestor=lancachenet/monolithic -q)
docker exec $docker_id /bin/bash -c "/data/prefill/SteamPrefill prefill" | tee $log

output=$(cat $log)

/usr/local/emhttp/plugins/dynamix/scripts/notify -e "Steam Prefill" -s "Steam Prefill run" -d "The prefill update run" -i "normal" -m "$output" -b

rm $log
```

**Possible Solution**
It would be nice to have an additional control flag to disable colours for terminals which do not support it.

Otherwise the application is awesome and super easy to use, thank you! :)

**Comment by tpill90** [comment]
Could you let me know the value of the `$TERM` variable is when ran inside the script?

**Comment by Bastians-Bits** [comment]
To be sure I've added this code to the script

```
echo "Term Parent: " $TERM
echo "Term Child: " $(docker exec $docker_id /bin/bash -c "echo $TERM")
```

both cases output

```
Term Parent: linux
Term Child: linux
```

**Comment by Bastians-Bits** [comment]
Just noticed that there is already a --no-ansi option for exactly that use-case, but doesn't get applied for all logging
<img width="593" alt="Screenshot 2023-12-26 at 21 05 19" src="https://github.com/tpill90/steam-lancache-prefill/assets/51163929/a71bfe22-3dbe-42de-9898-4e16d714a0ce">

**Comment by tpill90** [comment]
I'll take a look at the other text that isn't affected by `--no-ansi` and see whats going on with them.

While `--no-ansi` will mostly fix this issue, I do think that I need to take a deeper look into how to do this automatically, as this is not that uncommon of a question.  I'm wondering if the thing to do would be to detect that the terminal is non-interactive and use that to determine whether or not to display ansi codes.

I have a test build that has some debug output that I would like to see the results of.  Would you mind manually installing it and running your cron job as usual, and then sending over the output?  The build can be downloaded from this build job : 
https://github.com/tpill90/steam-lancache-prefill/actions/runs/7332865847

**Comment by Bastians-Bits** [comment]
I just want to hide under a rock somewhere :( I missed to put the arguments for SteamPrefill within the brackets passing it to the docker container :( I am so sorry to waste your time :(

With the latest release build and the flags correctly passed to the container
![Screenshot 2023-12-26 at 23 44 18](https://github.com/tpill90/steam-lancache-prefill/assets/51163929/428e0a6d-1fa3-45a5-8a13-aa248eef2ef2)

Thank you so much for your help and time, I really appreciate it! And again, I am so sorry :(

If you are still curious, that was the output of your build
![Screenshot 2023-12-26 at 23 41 35](https://github.com/tpill90/steam-lancache-prefill/assets/51163929/8c5b2463-5dcb-4773-a393-386fbbdcb30a)

Also, after a lot of debugging and testing on my side, I don't think anymore that the terminal has trouble with the colours, but the positioning of the cursor. If I disabled the colours hard-coded, it would still print the weird characters.

**Comment by tpill90** [comment]
I'm reopening this for the time being.  I think I'm going to add a faq entry for this and want to track that I get that added
