### ISSUE TITLE
Feature request: display year for games with the same title

### ISSUE THREAD

**Issue by dlrudie** [tpill90/steam-lancache-prefill#34]
Certain games may be re-released or be remade/remastered and share the same title. The list will just show both titles but you don't know which is which. Maybe check if there are multiple games that share the same title to display the year of the game afterwards.

![image](https://user-images.githubusercontent.com/1780069/182003180-22368f4d-6722-4b20-83b5-ec27df534dce.png)

Prey (2006)
Prey (2017)

**Comment by tpill90** [comment]
This should be covered in the most recent version, v1.3.2, using the new `select-apps-beta`.  See below image:
![image](https://user-images.githubusercontent.com/766513/186738922-4d2488c4-ed4d-4545-8180-0d0f3aa6ae6d.png)
