### ISSUE TITLE
Prefill failed: Manifest request timeout

### ISSUE THREAD

**Issue by Relnko** [tpill90/steam-lancache-prefill#343]
Happy new Year to @tpill90 and everyone else!

I have a Problem with Steam Prefill pretty similar to the already closed Issue [328](https://github.com/tpill90/steam-lancache-prefill/issues/328).
I don't know if this is a Steam Server problem or a Steam Prefill problem. The problem seems to have some kind of pattern.
Most of the time the prefill starts and the first app prefills flawless and all other apps cant be prefilled due to manifest request timeout. Sometimes (but rarely) all apps prefill without problems, but nothing inbetween like 3 out of x prefilled, always only 1 or all.

My Setup is the following:

x68 Pc with Unraid 6.12.5 installed running a lxc Container. (The lxc Container is running debian bullseye and is setup according to this [tutorial](https://forums.unraid.net/topic/135906-anleitung-unboundadguard-homelancache-lxc-container)(its in german) by @ich777) 
Im using crontab to start Steam Prefill with the follwing command:
`docker rm -f SteamPrefill &>/mnt/lancache && echo 'Removed old container from previous run';
docker run --rm --name SteamPrefill \
  --net=bridge \
  -e TZ="Europe/Berlin" \
  --add-host=lancache.steamcontent.com:192.168.178.76  \
  --volume /mnt/lancache/SteamPrefill:/Config \
  tpill90/steam-lancache-prefill:latest \
  prefill --verbose`

My region, if not obvious is Germany.
Discord: kekskuchen (formerly: Kekskuchen#5492)

Here the screenshots from my `app.log`:

![GitHubIssue1](https://github.com/tpill90/steam-lancache-prefill/assets/41121548/32921631-7b1c-4990-9b80-d0a1c3811759)
![GitHubIssue2](https://github.com/tpill90/steam-lancache-prefill/assets/41121548/d66b031b-a1e9-4bd3-a2b9-b7447b519ca0)

**Comment by ich777** [comment]
Have you yet tried to use the Docker container which is available in the CA App in Unraid?
You don't have to use prefill in the LXC Container since if you use the template from the CA App it is way more user friendly.


> 6.12.5

May I ask why you are not already on 6.12.6?

**Comment by Relnko** [comment]
> Have you yet tried to use the Docker container which is available in the CA App in Unraid?

Actually, no. Dont know why i didnt come up with this earlier... Will try it, but i can only prefill at night, or otherwise i slow down the intire internet for my house. So i will have to wait till tomorrow to see if it works.

> May I ask why you are not already on 6.12.6?

I couldnt get it to boot, always got checksum error. Used 6.12.5 and it worked without any issue.

**Comment by ich777** [comment]
> I couldnt get it to boot, always got checksum error. Used 6.12.5 and it worked without any issue.

I would strongly recommend checking your USB Boot device if it's still okay and if it isn't failing already if you got such an issue!

**Comment by Relnko** [comment]
Hello again. I installed your docker container and ran a prefill over night, and it seems to be working, except for some errors as you can see in the attached screenshot. Any idea what i can do about it?

![GitHubIssue3](https://github.com/tpill90/steam-lancache-prefill/assets/41121548/67a62809-8ea5-4102-bc13-da790096ec66)


> I would strongly recommend checking your USB Boot device if it's still okay and if it isn't failing already if you got such an issue!

To be honest i just grabbed a usb-stick i had lying around. I probaly will buy a new one.

**Comment by ich777** [comment]
> Any idea what i can do about it?

I think you'll have to wait for a response from @tpill90 about that error.



> To be honest i just grabbed a usb-stick i had lying around. I probaly will buy a new one.

No the best idea, I would recommend that you maybe buy something like a Transcend JetFlash 350 (or 600) USB2.0 16/32GB Flash device.

**Comment by tpill90** [comment]
> Hello again. I installed your docker container and ran a prefill over night, and it seems to be working, except for some errors as you can see in the attached screenshot. Any idea what i can do about it?
> 
> ![GitHubIssue3](https://private-user-images.githubusercontent.com/41121548/293937633-67a62809-8ea5-4102-bc13-da790096ec66.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTY3NDUsIm5iZiI6MTcwNDI5NjQ0NSwicGF0aCI6Ii80MTEyMTU0OC8yOTM5Mzc2MzMtNjdhNjI4MDktOGVhNS00MTAyLWJjMTMtZGE3OTAwOTZlYzY2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE1NDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZWU4OTQ3M2VjMzMyOTA4OGE3NTM0NzlmMmM5M2JlMDRiMjRkZmYxMGUxNDQyMWYyNGEyYzQyY2VlNTM4OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XBomHFOggUegpPk_PMhChJa0tal8mijV8sBpLLYdpU0)
> 
> > I would strongly recommend checking your USB Boot device if it's still okay and if it isn't failing already if you got such an issue!
> 
> To be honest i just grabbed a usb-stick i had lying around. I probaly will buy a new one.

Those kind of errors can sometimes be transient. It should switch over to another cdn and retry, but sometimes it doesn't always help. I'd give it a few hours, try again, and let me know if it keeps happening.

**Comment by Relnko** [comment]
@ich777 thanks for your help and recommendation!

@tpill90 the prefill completet, but around 5GB werent cached and had to be downloaded in the second run, so all good. Any thoughts on my initial post? Is the request timeout for the manifests a similar error?

**Comment by tpill90** [comment]
Could you attach your whole app.log for me here?

**Comment by Relnko** [comment]
If you want to see the app.log from my run inside the lxc container you can see it in the first post.

If you want to see the app.log from my last run with the docker container outside the lxc container you can see it here:

![GitHubIssue4](https://github.com/tpill90/steam-lancache-prefill/assets/41121548/3fb55bb5-75bd-4b3f-bedf-c0e969e06922)

**Comment by Relnko** [comment]
Hello again... It's been a while. I still get those errors, where the manifest request fails. My Unraid Server is now on 6.12.6 and SteamPrefill on 2.4.0. I tried it both in the LXC Container and in the CA App. I will try it tonight on my Windows PC.

Here a Screenshot from the app.log:
![GitHubIssue5](https://github.com/tpill90/steam-lancache-prefill/assets/41121548/24cac1c1-9540-444a-a844-d279d2ce7926)

**Comment by Relnko** [comment]
Im going to close this issue, because since the update to version 2.5.0 i haven't gotten this issue again, or atleast way less then before. Before it was >80% of apps that failed, now it's <10% and only when there are many apps that need to be prefilled. Most of the time it runs without any issues. Thanks alot @tpill90 for this great app!

**Comment by Relnko** [comment]
Im going to close this issue, because since the update to version 2.5.0 i haven't gotten this issue again, or atleast way less then before. Before it was >80% of apps that failed, now it's <10% and only when there are many apps that need to be prefilled. Most of the time it runs without any issues. Thanks alot @tpill90 for this great app!
