### ISSUE TITLE
Prefill not downloading SteamDeck shader cache

### ISSUE THREAD

**Issue by pascalschmiederer** [tpill90/steam-lancache-prefill#344]
Could it be that prefill only loads the Windows versions of Steam games?

Tested Game: Counter Strike 2

Mostly that's no Problem because you have the Proton layer and the Linux Steam Client loads the Windows game.
But for native Linux games you would need the prefill option "load Linux version"

**Additional Details**
 - Platform you are running SteamPrefill on:  Ich777's Unraid App
 - Region : [Germany]

**Comment by tpill90** [comment]
You'll want to use the `--os` flag to specify both Linux and windows. See [prefill docs](https://tpill90.github.io/steam-lancache-prefill/detailed-command-usage/Prefill/) for the full list of options

**Comment by pascalschmiederer** [comment]
Thank you very much and sorry for wasting your time. I hadn't seen that section yet!

**Comment by tpill90** [comment]
No worries at all!

**Comment by pascalschmiederer** [comment]
Once more: is it possible to download windows AND linux Versions with this paramter, or only Linux OR Windows?

"--os linux, windows" doesn't work?

**Comment by tpill90** [comment]
You can do both. Try it without the comma

**Comment by pascalschmiederer** [comment]
https://github.com/ich777/docker-lancache-prefill/issues/9

I crossposted the problem, because I don't know what is the correct repo to post. Sorry

**Comment by pascalschmiederer** [comment]
![Uploading Screenshot_20240113_114922.png…]()

**Comment by pascalschmiederer** [comment]
![Screenshot_20240113_114922](https://github.com/tpill90/steam-lancache-prefill/assets/9152178/c3af4fb3-1fff-455d-9f0d-7db683a83372)

**Comment by pascalschmiederer** [comment]
The prifill App says all the Files are up to date, but if I open Steam, there are no hits. 
There seams to be a bug in the linux update path. Or I do still something wrong. 

If I now uninstall CS2 from Steam, and reinstall it, I get the hits. Until there's a new update. Then I have to download the update again via Steam, because prefill says all up to date!

**Comment by tpill90** [comment]
I've been able to reproduce this using CS2 on Ubuntu. I'll try to figure out what's going on here

**Comment by tpill90** [comment]
I've confirmed that what you're seeing isn't the Linux version of the game, but its actually the shader predownloading that Steam now does for Linux.  

```
192.168.1.55 / - - - [18/Jan/2024:03:49:15 +0000] "GET /depot/730/manifest/1428942837211374601/5/9103427991922747470 HTTP/1.1" 200 84666 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache15-iad1.steamcontent.com" "-"
[steam] 192.168.1.55 / - - - [18/Jan/2024:03:49:15 +0000] "GET /depot/730/chunk/2866c3a8c143e48bd09f6a595dea83ddd69d6933 HTTP/1.1" 200 30640 "-" "Valve/Steam HTTP Client 1.0" "HIT" "cache15-iad1.steamcontent.com" "-"
[steam] 192.168.1.55 / - - - [18/Jan/2024:03:49:15 +0000] "GET /depot/730/chunk/9c1ccd54c3a5b296d8d514cef99f0ffb386f8c5b HTTP/1.1" 200 35872 "-" "Valve/Steam HTTP Client 1.0" "HIT" "cache15-iad1.steamcontent.com" "-"
[steam] 192.168.1.55 / - - - [18/Jan/2024:03:49:15 +0000] "GET /depot/730/chunk/b7827f00810fe9bc3131bc65858bd8b3e45adb39 HTTP/1.1" 200 30080 "-" "Valve/Steam HTTP Client 1.0" "HIT" "cache15-iad1.steamcontent.com" "-"
```

**Comment by tpill90** [comment]
Access log that shows app 730 downloading a manifest for what should be an app. 

[access.log](https://github.com/tpill90/steam-lancache-prefill/files/13982117/access.log)

**Comment by tpill90** [comment]
I've updated the issue title to better reflect whats going on here : SteamPrefill isn't downloading any shaders for the SteamDeck.

I'm going to close this issue out as I couldn't figure out exactly how Steam determines which shaders to download, as well as that this project is aimed at LAN parties where most machines are going to be running Windows. 

I am however open to merging in the changes to support this if anyone is willing to put in the effort to figure out how to implement shader downloading.
