### ISSUE TITLE
Bug: Titles missing

### ISSUE THREAD

**Issue by dlrudie** [tpill90/steam-lancache-prefill#35]
Certain titles that appeared previously are not appearing in 1.2.0.

One example is the game Into the Breach.

![image](https://user-images.githubusercontent.com/1780069/182003221-c5180c0e-e0a2-4ec7-9e91-80be6e36b364.png)

**Comment by dlrudie** [comment]
Another found is Mortal Kombat.

![image](https://user-images.githubusercontent.com/1780069/182003458-d491e414-0ab6-43b1-83fc-a31803832741.png)

![image](https://user-images.githubusercontent.com/1780069/182003462-4714c62e-3ab0-4163-88fd-0c326acc85aa.png)

**Comment by tpill90** [comment]
[SteamPrefill-1.2.0-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9227890/SteamPrefill-1.2.0-osx-x64.zip)
[SteamPrefill-1.2.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9227891/SteamPrefill-1.2.0-win-x64.zip)
[SteamPrefill-1.2.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9227892/SteamPrefill-1.2.0-linux-x64.zip)

**Comment by tpill90** [comment]
Adding package token to requests
[SteamPrefill-1.2.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9227944/SteamPrefill-1.2.0-linux-x64.zip)
[SteamPrefill-1.2.0-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9227945/SteamPrefill-1.2.0-osx-x64.zip)
[SteamPrefill-1.2.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9227946/SteamPrefill-1.2.0-win-x64.zip)

**Comment by spyfly** [comment]
Found some missing titles aswell:
- [Transport Fever 2](https://steamdb.info/app/1066780/)
- [Rainbow Six Siege](https://steamdb.info/app/359550/)

**Comment by tpill90** [comment]
Fixed in 1.2.1
