### ISSUE TITLE
[Feature Request] - Add support to use different branches on a app and support for downloading older manifests

### ISSUE THREAD

**Issue by nutterthanos** [tpill90/steam-lancache-prefill#356]
Hi
i would like a feature for adding options to steam-lancache-prefill to be use different branches on a app and support for downloading older manifests.

the way i was thinking was that before running through each app but after selecting unless they are already selected before hand it would ask for branchname otherwise if blank then defaults to public and if manifestid is also blank then run with what is in the latest appinfo.
and also by default it won't ask for either unless you put in a option to get it to tell you or something idk.

**Comment by tpill90** [comment]
As we discussed on Discord: this is outside the scope of SteamPrefill.  SteamPrefill aims to bulk download as much as possible as quickly as possible.  Different versions of apps on different branches are going to be on a case by case basis, and as such adding UI support for this would be difficult.
