### ISSUE TITLE
Feature request: prefill all to select the apps

### ISSUE THREAD

**Issue by dlrudie** [tpill90/steam-lancache-prefill#36]
If using prefill --all it may download all of the games but when you choose select-apps the games remain unselected. It would be nice to have it automatically mark the games downloaded as selected.

**Comment by tpill90** [comment]
This should be covered in the most recent version, v1.3.2, using the new `select-apps-beta`.  Using `CTRL-A` will allow you to select all games in the list.
![image](https://user-images.githubusercontent.com/766513/186739064-8a7d8af2-5df0-44a3-9f81-ea3d78be585e.png)
