### ISSUE TITLE
[Bug] select-apps locks up on Windows

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#366]
Select-apps locks up on Windows.  It is impossible to exit the app with ESC or to kill it with ctrl+c.  This issue occurs on both Powershell and Windows Terminal

**Comment by noshricardo** [comment]
Is their a way around this? Should I use an older version? or should I just run it on Linux?

**Comment by tpill90** [comment]
Testing this some more it doesn't appear to be related to a change in SteamPrefill.  Regardless of the version that I use it still locks up when running in Windows Terminal.  If I switch over to using a plain CMD prompt it works as expected.

**Comment by tpill90** [comment]
Released in [v2.6.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.6.0)
