### ISSUE TITLE
[Feature Request] Check Cached Content

### ISSUE THREAD

**Issue by Orski174** [tpill90/steam-lancache-prefill#383]
I recently had to change the VM that SteamPrefill was running in, after setting it all up I noticed that it was re-downloading stuff again.

So an option to scan/check what's downloaded is really appreciated, I guess this is probably a duplicate of #354 but from a different approach.

Thanks!!

**Comment by tpill90** [comment]
Could you clarify a few things for me?  From what I'm understanding you had an existing instance of SteamPrefill, and then you created and setup a second instance of it on another VM?  And you had already prefilled some stuff prior to creating that second instance?

**Comment by Orski174** [comment]
Yes, though I removed the first instance. That instance had lancache and SteamPrefill running, I reinstalled both on a new vm pointing to the same cache of course then ran the prefill task and instead of continuing it started over.

**Comment by tpill90** [comment]
When you ran the second prefill was it much faster than before?  Was it faster than your internet connection?

**Comment by Orski174** [comment]
That's what I thought it would do, when an incomplete download gets interrupted in the prefill process SteamPrefill usually starts from there and rescans the files for it. That unfortunately didn't happen, it was downloading.

**Comment by tpill90** [comment]
How difficult is it for you to reproduce this again by creating a new VM like you did before? I have an idea I'd like to try

**Comment by Orski174** [comment]
Not difficult at all, with another lancache or the same one?

**Comment by tpill90** [comment]
> Yes, though I removed the first instance. That instance had lancache and SteamPrefill running, I reinstalled both on a new vm pointing to the same cache of course then ran the prefill task and instead of continuing, it started over.

I'd like you to do the same thing that you did here, but instead of using SteamPrefill download something that should already be cached via steam. And watch the access logs for lancache to see what is hitting the cached data and what isn't.

**Comment by Orski174** [comment]
Could it be that the new lancache isn't identifying the old cache?

**Comment by tpill90** [comment]
I'm still not clear on what you mean by new cache and old cache. 

Do you happen to have discord?  If you do would you mind joining our server and chatting about this issue there a little bit?  I think we could get this figured out a bit quicker in chat, and we can post the resolution here when we're finished.

**Comment by Orski174** [comment]
It was a mountpoint typo :)
