### ISSUE TITLE
Demo/Closed Beta's seem to not allow prefill

### ISSUE THREAD

**Issue by michaelkr1** [tpill90/steam-lancache-prefill#388]
**Describe the bug**
-  Two games, which are both closed beta and a demo respectively do not show up for Prefill. Both of these games are quite popular at the moment and would benefit from being prefillable (Delta Force alone is 45GB download).
-  Game 1: Deadlock - https://store.steampowered.com/app/1422450/Deadlock/
-  Game 2: Delta Force - https://store.steampowered.com/app/2507950/Delta_Force/  
-  I'm not sure if this is a Steam side issue or whether the prefill app is filtering out demos and betas.

**Additional Details**
 - Platform you are running SteamPrefill on:   Ich777's Unraid App
 - Discord Username (if you are part of the Lancache Discord Server) : Not part of the server but username: Wranger

**Comment by tpill90** [comment]
Good catch!  Thanks for the report.

I've figured out a fix and will get this pushed up in the next release I do.

**Comment by tpill90** [comment]
Released in [v3.0.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v3.0.0)

**Comment by tpill90** [comment]
Reopened as this has introduced a bug where some games that should be included are being filtered out.

**Comment by tpill90** [comment]
Second fix was released in [v3.1.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v3.1.0)

**Comment by Vinfall** [comment]
Looks like there is a regression in v3.4.2 as I can't prefill demos.

Demos does not show up with `SteamPrefill select-apps`. When I manually edit `selectedAppsToPrefill.json` with the right AppId, `SteamPrefill select-apps status` still reports 0 byte and of course `SteamPrefill prefill` does not download anything.

- Tested AppIds: 4161460, 4173250
- Platform: Void Linux x86_64-glibc

**Comment by tpill90** [comment]
Released in [v3.5.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v3.5.0)
