### ISSUE TITLE
[Docs] Typo in clear-temp options description on github.io wiki.

### ISSUE THREAD

**Issue by jh2000** [tpill90/steam-lancache-prefill#391]
In the description of the options to the clear-temp subcommand on https://tpill90.github.io/steam-lancache-prefill/detailed-command-usage/Clear-Temp/ it says "Clears the temp files immediately, displaying a prompt."
The intention of  --yes is to display no prompt, so it should be "... displaying no prompt."
I couldn't figure out how to correct it there, sorry if i somehow could have done that by myself .

The whole options subsection should just show the same as the "./SteamPrefill clear-temp --help" output
Therefore:
```
-y|--yes          When specified, will clear the temp files without prompting.
-h|--help         Shows help text.
```

Thanks for the good documentation and a really handy tool!

**Comment by tpill90** [comment]
Thanks for the heads up!  I'll get this updated

**Comment by tpill90** [comment]
Done!  Thank you!
