### ISSUE TITLE
Error Code: "System.FormatException: eStateUnavailable is not a valid enum value for ReleaseState!"

### ISSUE THREAD

**Issue by ChrSch84** [tpill90/steam-lancache-prefill#49]
Hello,
got this Error Message on the every Version.

"SteamPrefill.exe select-apps"

![image](https://user-images.githubusercontent.com/30344592/182595818-d7f1380b-2c2f-45b7-813b-ba616766e682.png)

Test was on a Linux AND a Windows System. Both the same Error.

**Comment by tpill90** [comment]
[SteamPrefill-1.2.1-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9251185/SteamPrefill-1.2.1-linux-x64.zip)
[SteamPrefill-1.2.1-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9251186/SteamPrefill-1.2.1-win-x64.zip)

**Comment by tpill90** [comment]
Fix merged in #53

**Comment by tpill90** [comment]
Released in v1.2.2
