### ISSUE TITLE
Failed to save Steam session key.  Steam account will not stay logged in

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#56]
When logging in, sometimes Steam will fail to save the session and will show the following error : 

![image](https://user-images.githubusercontent.com/766513/182922574-b319de0f-0dd3-4ea9-801a-00ce50979744.png)

This issue prevents users from being able to use the app without logging in every time, which also prevents the use of this app in a cron job.

## Findings so far

- When using the Lancache with two copies of SteamPrefill, logging into the first copy will cause the second to be kicked out.  Then logging in with the second one will cause the first one to be kicked out.
- If I disable the Lancache, then the above no longer occurs.
- Removing the `Logout()` call in `Steam3Session.cs` seems to prevent other login sessions from getting bounced.  Tested by logging into multiple SteamPrefill instances, waiting over the weekend, and then running SteamPrefill Monday morning.  No SteamPrefill instances were logged out.
- The "Failed to save Steam session key" seems to be reliably reproducible by logging into multiple instances of SteamPrefill back-to-back.  They appear to go away after a certain period of time, it may be Steam throttling logins.

**Comment by dlrudie** [comment]
When switching between prefill and select-apps I will occasionally run into an issue where it will not be able to save the Steam session and require me to log in each time. Additionally, when running just prefill every 3 runs or so it will ask me to sign back in.

![image](https://user-images.githubusercontent.com/1780069/182922666-bf1c3e1b-2433-4630-aab5-4618434b2487.png)

**Comment by tpill90** [comment]
This issue only occurs for me occasionally, maybe every few days at most.  It usually resolves itself on its own if I wait between 5 to 30 minutes.

**Comment by tpill90** [comment]
[SteamPrefill-1.2.2-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9265079/SteamPrefill-1.2.2-win-x64.zip)
[SteamPrefill-1.2.2-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9265081/SteamPrefill-1.2.2-linux-x64.zip)

**Comment by spyfly** [comment]
> [SteamPrefill-1.2.2-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9265079/SteamPrefill-1.2.2-win-x64.zip) [SteamPrefill-1.2.2-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9265081/SteamPrefill-1.2.2-linux-x64.zip)

Issue still persists in the latest version

**Comment by tpill90** [comment]
Fix merged in #59 .  Will be included in next release.

**Comment by EthRousseau** [comment]
I know that I have been logged out at least once in the past, which I realized when trying to set up a cron job. That cron job also does not give any alert that something is wrong if it fails, and I only could know that there was an issue if I looked at the logs for the job (which I manually set up)

**Comment by spyfly** [comment]
Seems to work now, haven't had any logouts since the update to the new version.

**Comment by tpill90** [comment]
@EthRousseau I created a new issue for the cron job issue that you're running into, since it seems that the issue isn't specifically the logout, but rather the fact that there is no notification that something went wrong.
 https://github.com/tpill90/steam-lancache-prefill/issues/76.

**Comment by tpill90** [comment]
I'm closing this issue for now, since there has been multiple reports that logouts are not happening as frequently.
