### ISSUE TITLE
[Feature Request] Provide Docker Container Image

### ISSUE THREAD

**Issue by spyfly** [tpill90/steam-lancache-prefill#58]
Enables automatic updates, using software such as watchtower.

**Comment by SamTV12345** [comment]
Great idea. I'm going to check this out.

**Comment by SamTV12345** [comment]
Somebody was faster than me. Please have a look at https://gitlab.com/kirbo/steam-prefill-docker .

**Comment by tpill90** [comment]
Closing this issue, as its a duplicate of https://github.com/tpill90/steam-lancache-prefill/issues/94 which was created to integrate Kirbo's repo into this one, to officially support Docker
