### ISSUE TITLE
Unexpected download error : Unable to get available CDN servers from Steam

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#6]
`SteamPrefill` seems to be unable to find any any regional CDNs when running from **Australia**, preventing it from moving on from the logon stage.

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/180050601-b3f17ffe-fcc7-4343-bca5-7073ec13bf1c.png)

**Comment by tpill90** [comment]
@nightah I think I've got a solution to this, tested this build using a VM hosted in Australia.

[linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9154811/linux-x64.zip)
[win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9154810/win-x64.zip)

**Comment by ishkanan** [comment]
Yep just tested it from AU @tpill90 and everything is working 👍🏼

**Comment by Hannsre** [comment]
Just gave it a go after reinstalling LC. 
Got this error on first try, on second try it worked fine. 

![image](https://user-images.githubusercontent.com/81830618/180315617-0f7e59f6-cfeb-484a-a793-f421e9ae3ba3.png)

**Comment by tpill90** [comment]
> 

I think that I also took care of this issue at the same time.  I had to finish reworking other parts of the app that use the CDNs, that I didnt finish in that build.  

I'm going to close this issue, as I've merged in the fix for this.  If the issue comes back up then feel free to reopen.
