### ISSUE TITLE
[Feature] Select-apps interface redesign feedback

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#60]
Feedback desired

- [x] Navigation
  - [x] Is the navigation intuitive?  Does it make sense without reading documentation?
  - [x] Is there anything frustrating about trying to navigate?
- [ ] Could the text coloring be modified in any way that would make it easier to read?
- [ ] Update documentation
- [ ] Switch `select-apps` over to using new beta interface
- [ ] Add a notice to `select-apps-beta` that command is deprectated.

**Comment by tpill90** [comment]
[SteamPrefill-1.2.2-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9294651/SteamPrefill-1.2.2-win-x64.zip)
[SteamPrefill-1.2.2-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9294652/SteamPrefill-1.2.2-linux-x64.zip)

**Comment by Velosofy** [comment]
Version : Linux v1.3.1
Games with Chinese/Japanese title has a weird year/type formatting

![image](https://user-images.githubusercontent.com/61261357/185747936-391ef082-80cd-45aa-981c-7390ec06cb1c.png)

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/186929608-36fe6af2-47e4-4a5c-a97a-9b0b214ba0b0.png)
![image](https://user-images.githubusercontent.com/766513/186929638-a177185a-0830-46e9-8ed1-39fb784607c5.png)

**Comment by tpill90** [comment]
![image](https://user-images.githubusercontent.com/766513/186931527-774ff4a9-fc42-4ec0-8189-9324579a749f.png)
![image](https://user-images.githubusercontent.com/766513/186931549-a4473672-3647-481a-acf0-4837e06f2058.png)
@dlrudie

**Comment by tpill90** [comment]
Released in [v1.6.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.6.0)
