### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by haouarihk** [tpill90/steam-lancache-prefill#61]
Hi,
It would be really cool if i can run this script on my low powered raspberry pi,
so that i don't need my main pc to download games overnight,
it will be comparing 4w power consumption to 100w.

hardware:
pi4B
- 4GB of ram
- 64bit system

thanks

**Comment by tpill90** [comment]
[SteamPrefill-1.2.2-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9320646/SteamPrefill-1.2.2-linux-arm64.zip)

**Comment by haouarihk** [comment]
i can confirm that the build works

**Comment by tpill90** [comment]
Released in https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.3.0
