### ISSUE TITLE
(Synology x64) libstdc++.so.6: no version information available

### ISSUE THREAD

**Issue by rwesterflan** [tpill90/steam-lancache-prefill#7]
While running the tool, this error gets returned:

`./SteamPrefill: /lib/libstdc++.so.6: no version information available (required by ./SteamPrefill)`
DSM 6.2.3-25426

**Comment by tpill90** [comment]
How to run DSM on VMWare

https://xpenology.com/forum/topic/13061-tutorial-install-dsm-62-on-esxi-67/
https://xpenology.com/forum/topic/31105-wetjets-easy-all-in-one-ds3617-tutorial-for-esxi-67/

**Comment by tpill90** [comment]
I've done some more digging into this, and it looks like this isn't something I'm going to be able to resolve on my end, at least within the dotnet tooling.

There is a related issue on the dotnet runtime repo : [dotnet/runtime/issues/33384](https://github.com/dotnet/runtime/issues/33384)  From reading that issue it seems like the only solution will to either install `libstdc++` manually, or hope that the package gets included in a newer version of DSM.

I'm leaving the issue open for now, so other people with the same issue can see that this is still outstanding.

**Comment by tpill90** [comment]
Closing this issue, as it looks like this is something that is ultimately not able to be solved inside this project.
