### ISSUE TITLE
First run: hangs on 'connecting to Steam'

### ISSUE THREAD

**Issue by rwesterflan** [tpill90/steam-lancache-prefill#8]
After logging in with username/password and 2FA, the client gets stuck on the `Connecting to Steam` prompt

**Comment by tpill90** [comment]
This issue seems to stem from a missing timeout that could cause a hang when attempting to connect to Steam.

Added a timeout in #26 .  Will close this issue once this is included in the next release

**Comment by tpill90** [comment]
Released in [v.1.2.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.2.0)

**Comment by TurboSlayer** [comment]
This issue seems to occur 100% of the time when logging in from certain parts of Asia. Below is a list of Tunnelbear VPN regions that cause/do not cause a timeout:

Login **times out** on these servers:

- Taiwan
- Philippines

Login **works** on these servers:

- US
- South Korea
- Japan
- Indonesia
- Singapore
- Australia
- Malaysia
- New Zealand
- Nigeria
- Kenya
- South Africa
- Argentina
- Mexico

**Comment by tpill90** [comment]
Test build to see if it resolves the issue
[SteamPrefill-1.2.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9235974/SteamPrefill-1.2.0-linux-x64.zip)
[SteamPrefill-1.2.0-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9235975/SteamPrefill-1.2.0-osx-x64.zip)
[SteamPrefill-1.2.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9235976/SteamPrefill-1.2.0-win-x64.zip)

**Comment by tpill90** [comment]
[SteamPrefill-1.2.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9236398/SteamPrefill-1.2.0-win-x64.zip)
[SteamPrefill-1.2.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9236399/SteamPrefill-1.2.0-linux-x64.zip)

**Comment by tpill90** [comment]
Fix merged in #40

**Comment by tpill90** [comment]
[SteamPrefill-1.2.1-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9244415/SteamPrefill-1.2.1-osx-x64.zip)
[SteamPrefill-1.2.1-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9244416/SteamPrefill-1.2.1-win-x64.zip)
[SteamPrefill-1.2.1-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9244417/SteamPrefill-1.2.1-linux-x64.zip)

**Comment by tpill90** [comment]
Another fix was merged in with #42

**Comment by tpill90** [comment]
Released in v1.2.2
