### ISSUE TITLE
[Bug] Some games aren't listed in prefill

### ISSUE THREAD

**Issue by Velosofy** [tpill90/steam-lancache-prefill#82]
Some games that I want to prefill aren't showing up in SteamPrefill

I only check for this specific title for now though...

version : Linux v1.31
![image](https://user-images.githubusercontent.com/61261357/185747695-aea8675a-6cf9-49e1-ba5c-4d5ec59792be.png)

**Comment by tpill90** [comment]
[SteamPrefill-1.4.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9463543/SteamPrefill-1.4.0-linux-x64.zip)
[SteamPrefill-1.4.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9463545/SteamPrefill-1.4.0-win-x64.zip)

**Comment by tpill90** [comment]
Released in v1.5.0
