### ISSUE TITLE
[Enhancement] Adding found local IP addresses for the lancache.steamcontent.com address

### ISSUE THREAD

**Issue by Edwin-Dijk** [tpill90/steam-lancache-prefill#87]
After some confusion about the message that a server was found at lancache.steamcontent.com this idea got put up in the discord. 
Mentioning the actual address the caching server was found at might stop some confusion.
![image](https://user-images.githubusercontent.com/33722378/185925181-0ea8f74e-36f5-4511-a3fd-806fce4a2490.png)
![image](https://user-images.githubusercontent.com/33722378/185925438-da03235f-d712-40fc-b472-5da8c16c8446.png)

**Comment by tpill90** [comment]
Added the resolved IP address to the following message:
![image](https://user-images.githubusercontent.com/766513/189434838-83b0498a-adf2-44a8-97fb-a5fef5c2e50b.png)
![image](https://user-images.githubusercontent.com/766513/189434898-0b3a1d8c-abf5-4a49-a57e-3700766b6115.png)
