### ISSUE TITLE
Wrong False / Positive with AV Scanner (Win 11 Defender mybe more)

### ISSUE THREAD

**Issue by ChrSch84** [tpill90/steam-lancache-prefill#88]
**_**First of all:
There is NO VIRUS it is only a FALSE ALARM**_**

The Problem:

With the Prefill File Version: SteamPrefill-1.3.1-win-x64 and Windows 11 and Defender:

Defender Security Update from 22.08.2022 12:48 Versions Number: 1.373.806.0

you can get a False/Postive Virus Found.

It is not Possible to access the File in Windows 11 or even download it. Chromium Browser no download, Firefox Download but no Access to File.

The Hash of the File should be: (Check with Powershell)

---------------------------

Get-FileHash .\SteamPrefill-1.3.1-win-x64.zip

Algorithm       Hash                                                                   

SHA256         6491C77C3778B2A2FE3D3A2172945742A5A5AF163311F3D1C0E1EEBE65DFD8D8

---------------------------
Error Message be like that in Windows:

![image](https://user-images.githubusercontent.com/30344592/186029257-d586c880-03bd-40f2-bab9-528d5f191750.png)

**Comment by tpill90** [comment]
Tested this with two machines against v1.4.0.  Smart Screen appears to no longer flag the file as malicious.
