### ISSUE TITLE
Statically linked binaries for linux

### ISSUE THREAD

**Issue by koenvdheuvel** [tpill90/steam-lancache-prefill#92]
Hi,

Would it be possible to build the app with static links so that it could run any distro?

Trying to run this on alpine which doesn't have glibc but musl libc :)

**Comment by tpill90** [comment]
[SteamPrefill-1.3.2-linux-musl-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9429015/SteamPrefill-1.3.2-linux-musl-x64.zip)

**Comment by tpill90** [comment]
I believe that it is not currently possible to publish statically linked dependencies such as `libstdc++` with the current dotnet toolchain.
Taking a look at https://github.com/dotnet/runtime/issues/33384 it seems that the recommended approach from the dotnet team is to install the required dependencies for Alpine, as follows: 
`apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib`

I could possibly do one of the following to help with this issue in the future:
- Add documentation to the install section of the readme, detailing that additional dependencies are required for Alpine
- Or, alternatively suggest in the documentation an alternative method of running the app on Alpine.  Such as using a different distro's Docker image, or using one of the community provided images for SteamPrefill.

**Comment by tpill90** [comment]
Added instructions to the readme on how to install required dependencies for alpine linux : ![image](https://user-images.githubusercontent.com/766513/187733762-95865f80-c3aa-4efc-a3f3-e56939a8a2bc.png)

Closing this issue as there is no way to include these binaries with the dotnet toolchain
