### ISSUE TITLE
Crash in 1.3.2 related to key not in dictionary

### ISSUE THREAD

**Issue by dlrudie** [tpill90/steam-lancache-prefill#95]
I receive a crash when using 1.3.2.

This happens when using both select-apps and select-apps-beta.

![image](https://user-images.githubusercontent.com/1780069/186705239-6f6d4684-ad75-4594-853c-ce4cb6cbd50d.png)

**Comment by tpill90** [comment]
Test build 
[SteamPrefill-1.3.2-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9426710/SteamPrefill-1.3.2-win-x64.zip)
[SteamPrefill-1.3.2-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9426711/SteamPrefill-1.3.2-linux-arm64.zip)
[SteamPrefill-1.3.2-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9426713/SteamPrefill-1.3.2-linux-x64.zip)
[SteamPrefill-1.3.2-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9426709/SteamPrefill-1.3.2-osx-x64.zip)

**Comment by petecog** [comment]
I observed the same on win and linux.

**Comment by petecog** [comment]
Also seems to occur on 1.3.3. Is there perhaps some dependency that me and @dlrudie are missing?

```
~/SteamPrefill-1.3.3-linux-x64# ./SteamPrefill select-apps
╭─────────────────────────────────────────────────────────────╮
│                                                             │
│ select-apps is getting a new look!                          │
│ Try it out now with select-apps-beta!                       │
│                                                             │
│ Please direct beta feedback to :                            │
│ https://github.com/tpill90/steam-lancache-prefill/issues/60 │
│                                                             │
╰─────────────────────────────────────────────────────────────╯
[7:19:44 AM] Starting login!
A Steam account is required in order to prefill apps!
Please enter your Steam account name : yogakills
Please enter your Steam password. (Password won't be saved) : *************
This account is protected by Steam Guard.  Please enter the code sent to your email address: CVGXB
[7:20:07 AM] Logged into Steam
[7:20:08 AM] Steam session initialization complete!
System.Collections.Generic.KeyNotFoundException: The given key '414160' was not present in the dictionary.
  at void System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey )
  at TValue System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey )
  at async Task<AppInfo> SteamPrefill.Handlers.AppInfoHandler.GetAppInfoAsync(uint appId)
  at async Task<List<AppInfo>> SteamPrefill.Handlers.AppInfoHandler.GetGamesById(List<uint> appIds)
  at async Task<List<AppInfo>> SteamPrefill.SteamManager.GetAllAvailableGamesAsync()
  at async Task SteamPrefill.SteamManager.SelectAppsAsync()
  at async ValueTask SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)
```

**Comment by tpill90** [comment]
This should be fixed in the recent v1.3.4 release.

**Comment by petecog** [comment]
1.3.4 on Linux looks good now! Many thanks

**Comment by tpill90** [comment]
> 1.3.4 on Linux looks good now! Many thanks
@petecog 
I believe that this issue is directly related to #100
I've pushed up a test build in the link below.  Could you try it and test to see that it doesn't crash for you, as well as confirming that appid [414160](https://steamdb.info/app/414160/) **Nubarron: The adventure of an unlucky gnome** shows up in your list of available games?

https://github.com/tpill90/steam-lancache-prefill/issues/100#issuecomment-1229248200

**Comment by petecog** [comment]
Testing the build linked above.

Nubarron - appears. 
![image](https://user-images.githubusercontent.com/5559530/187390125-4e50e2a4-212c-48c9-8bec-a03752b7befe.png)

and prefills ok
![image](https://user-images.githubusercontent.com/5559530/187390324-e16f80b2-220e-42fb-ab87-93dbb746010a.png)

**Comment by tpill90** [comment]
Thank you for testing @petecog
Closing this as the fix has been released in https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.4.0
