### ISSUE TITLE
Prefill hanging after completing

### ISSUE THREAD

**Issue by EthRousseau** [tpill90/steam-lancache-prefill#96]
Using v1.3.2 in x86 Linux

After prefilling it gives the message "already disconnected from steam" and does not return to the terminal prompt after finishing.

![image](https://user-images.githubusercontent.com/41489473/186709303-9615a18e-d904-471a-ae25-2274a9b549f4.png)

**Comment by tpill90** [comment]
[SteamPrefill-1.3.2-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9426377/SteamPrefill-1.3.2-linux-x64.zip)
[SteamPrefill-1.3.2-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9426380/SteamPrefill-1.3.2-win-x64.zip)
